apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-app
  labels:
    app: my-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend-app
  template:
    metadata:
      labels:
        app: my-backend-app
    spec:
      containers:
      - name: app
        image: public.ecr.aws/k8c9l4n1/mybackendapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3004
        env:
        - name: RDS_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: RDS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: mysql-host
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:462242201169:certificate/b7dfcb85-2d18-407f-829f-80db2e2bcbd4
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: my-backend-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3004
