apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-configmap
data:
    mysql-dbname: mynode_db
    mysql-host: mysql-service
---
apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-root-password: cXdlcnRAMDk4NzY=
    mysql-user: YXBw
    mysql-password: cXdlcnRAMDk4NzY=
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
